source 'https://rubygems.org'

gem "jekyll", "~> 4.3" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2


gem "just-the-docs"  
gem "jekyll-remote-theme"          # the latest release - currently 0.3.3